
// Major field key -> display label. Keys come from the Major nodes' `fields` (see backend/db_setup/major_specs.py
// and the initialize_*_major.py scripts); unknown keys are shown as-is.
const FIELD_LABELS: Record<string, string> = {
    prereq: 'Prerequisites',
    elective: 'Electives',
    core: 'Core',
    integration: 'Integration Electives',
    general: 'General Electives',
    computing: 'Computing Electives',
    aip: 'Artistic, Interpretive, and Philosophical Inquiry',
    cmp: 'The Chemical, Mathematical, and Physical Universe',
    csw: 'Cultures and Societies of the World',
    hp: 'Historical Perspectives',
    ls: 'Living Systems',
    ss: 'Science and Society',
    ses: 'Social and Economic Systems',
    writing1: 'First Writing Requirement',
    writing2: 'Second Writing Requirement',
    foundations: 'Engineering Foundations',
    calculus: 'Calculus',
    chemistry: 'Chemistry',
    physics: 'Physics',
    programming: 'Introduction to Programming',
    sts: 'Science, Technology, & Society',
    mathsci: 'Math/Science Elective I',
    hss: 'Humanities & Social Science Electives',
    capstone: 'Capstone',
    apma: 'Applied Math Electives',
    math: 'Mathematics',
    mathelective: 'Math Elective',
    engineering: 'Engineering Electives',
    technical: 'Technical Electives',
    ece: 'Electrical & Computer Engineering',
    cs: 'Computer Science',
    design: 'Major Design Experience',
    advanced: 'Advanced Courses',
    american: 'American Politics',
    analysis: 'Data Analysis Electives',
    application: 'Planning Applications',
    applied: 'Applied Coursework',
    arthistory: 'Art History',
    behavioral: 'Behavioral & Cognitive Neuroscience',
    belief: 'Belief & Thought',
    cct: 'Composition & Creative Technology',
    cellular: 'Cellular & Molecular Neuroscience',
    civic: 'Civic & Political Contexts',
    civilization: 'Civilization',
    clinical: 'Clinical & Social Psychology',
    clinicalexp: 'Clinical Experiences & Seminars',
    cognitive: 'Cognitive Psychology',
    collaborative: 'Collaborative Concentrations',
    commerce: 'Global Commerce in Culture & Society',
    communication: 'Developmental Communication Sciences',
    comparative: 'Comparative Politics',
    computational: 'Computational Electives',
    concentration: 'Concentration',
    context: 'Wider Context',
    corequisite: 'Co-Requisites',
    crafting: 'Crafting Performance',
    creating: 'Creating Performance',
    critical: 'Critical Studies',
    cultural: 'Cultural Literacy',
    culture: 'Language, Literature & Culture',
    departmental: 'Departmental Electives',
    development: 'Global Development Studies',
    developmental: 'Developmental Psychology',
    discovery: 'Discovery',
    distribution: 'Distributional Electives',
    diversity: 'Diversity & Inclusion',
    economic: 'Economic Analysis',
    finance: 'Finance Electives',
    focused: 'Focused Inquiry',
    folklore: 'Folklore',
    foundation: 'Foundation Courses',
    gateway: 'Gateway Courses',
    global: 'African, Asian & Indigenous Traditions',
    greek: 'Greek',
    historical: 'Historical Linguistics',
    history: 'History',
    humanities: 'Humanities & Social Sciences',
    inquiry: 'Conduct of Inquiry',
    international: 'International Relations',
    interpretation: 'Interpretation & Invention',
    intro: 'Introductory Course',
    lab: 'Laboratory',
    language: 'Language',
    latin: 'Latin',
    leadership: 'Leadership',
    linguistics: 'Linguistics',
    literature: 'Literature',
    logic: 'Logic',
    major: 'Major Coursework',
    mathcs: 'Advanced Math/CS Elective',
    mesa: 'Global Middle East & South Asia',
    methods: 'Research Methods & Data Analysis',
    modern: 'Modern Period',
    moral: 'Moral Philosophy',
    musicianship: 'Musicianship',
    neuroscience: 'Neuroscience',
    performance: 'Performance',
    period1700: 'Literature 1700-1900',
    philosophy: 'Philosophy',
    policy: 'Policy',
    politics: 'Politics Electives',
    populations: 'Special Populations',
    practice: 'Practice',
    practicum: 'Practicum',
    premodern: 'Pre-Modern Period',
    preservation: 'Historic Preservation',
    professional: 'Professional Electives',
    psychology: 'Psychology',
    publichealth: 'Public Health',
    quantitative: 'Quantitative Requirements',
    regional: 'Regional Concentration',
    related: 'Related Courses',
    research: 'Research',
    rmtopics: 'Research Methods Topics',
    rntobsn: 'RN to BSN',
    science: 'Science',
    security: 'Global Security & Justice',
    seminar: 'Seminar',
    social: 'Social & Political Philosophy',
    structure: 'Language Structure',
    studies: 'Area Studies',
    supporting: 'Supporting Courses',
    survey: 'Surveys',
    sustainability: 'Global Sustainability',
    theoretical: 'Theoretical Foundations',
    theory: 'Theory',
    thesis: 'Thesis',
    topical: 'Topical Electives',
    topics: 'Topics',
    track: 'Track Electives',
    upper: 'Upper-Level Electives',
    values: 'Values, Culture & History',
    workshop: 'Introductory History Workshop',
    // sub-fields, and the fields they belong to
    abstractalgebra: 'Abstract Algebra',
    archaeology: 'Archaeology',
    biology: 'Biology',
    calc2: 'Calculus II',
    calcstats: 'Calculus or Statistics',
    coreareas: 'Core Areas',
    diffeq: 'Differential Equations',
    distributionreq: 'Distribution Requirements',
    dsfoundation: 'Foundation of Data Science',
    fundamentals: 'Fundamentals',
    interdisciplinary: 'Interdisciplinary Core',
    intermicro: 'Intermediate Microeconomics',
    introstats: 'Introductory Statistics',
    latinamerica: 'Latin American Literature & Culture',
    law: 'Commerce Law',
    learningareas: 'Learning Areas',
    linalg: 'Linear Algebra',
    linguistic: 'Linguistic',
    performancereq: 'Performance Requirement',
    realanalysis: 'Real Analysis',
    required: 'Required Courses',
    restricted: 'Restricted Electives',
    sciencefoundation: 'Science Foundation',
    secondyear: 'Second Year',
    sociocultural: 'Sociocultural',
    spain: 'Spanish Literature & Culture',
    statistics: 'Statistics',
    thirdyear: 'Third Year',
};

const label = (key: string) => FIELD_LABELS[key] ?? key;

// Sub-field keys look like "linalg (core)" and are shown as "Linear Algebra (Core)"
export function formatFields(fieldList: string[]) : string[] {
    return fieldList.map((field) => {
        const sub = field.match(/^(.+) \((.+)\)$/);
        return sub ? `${label(sub[1])} (${label(sub[2])})` : label(field);
    });
}
